[tools]
go = "1.25.0"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"cargo:git-cliff" = "latest"

[env]
GOBIN = "{{config_root}}/bin"

[settings]
sops.strict = false
experimental = true
lockfile = true
