name: Notary
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Check format
        run: mise run fmt

      - name: Lint
        run: mise run lint

      - name: Build
        run: mise run build

      - name: Test
        run: mise run test
