name: Notary
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Check format
        run: mise run fmt

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Run linter
        run: mise run lint

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Build binary
        run: mise run build

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true

      - name: Run tests
        run: mise run test
